site_name: Biasbuster Documentation
site_description: AI-powered platform for detecting and mitigating bias in content
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture.md
    - System Design: system-design.md
    - API Documentation: api.md
  - User Guide:
    - Getting Started: user-guide.md
    - Chrome Extension: chrome-extension.md
    - Web Platform: web-platform.md
    - Analytics Dashboard: analytics-dashboard-guide.md
  - Developer Guide:
    - Contributing: CONTRIBUTING.md
    - Development Setup: DEVELOPER.md
    - Code Style: style-guide.md
    - Testing: testing-guide.md
  - BMAD Methodology:
    - Overview: bmads/bmads-methodology.md
    - Stories: bmads/stories/
    - Personas: bmads/personas/
    - Tasks: bmads/tasks/
  - Project Management:
    - Project Charter: project-management/project-charter.md
    - Business Case: project-management/business-case.md
    - Risk Register: project-management/risk-register.md
  - Compliance & Legal:
    - Privacy Policy: compliance/privacy-policy.md
    - Terms of Service: compliance/terms-of-service.md
    - Security Policy: SECURITY.md
    - Licenses: legal/open-source-licenses.md
  - About:
    - Mission & Vision: startup/mission-vision-values.md
    - Release Notes: release-notes.md
    - FAQ: faq.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
  - minify:
      minify_html: true
  - social:
      cards_color:
        fill: "#7E56C2"
        text: "#FFFFFF"

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/biasbuster
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/biasbuster
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
