# Biasbuster Knowledge Base Configuration

# AI Integration Settings
ai:
  search:
    engine: "elasticsearch"
    nlp_model: "gpt-4"
    embeddings_model: "all-mpnet-base-v2"
    similarity_threshold: 0.85
    context_window: 2048
    
  recommendations:
    model: "collaborative-filtering"
    min_confidence: 0.75
    max_suggestions: 5
    
  content_generation:
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 4096
    
  auto_tagging:
    model: "bert-base-multilingual"
    confidence_threshold: 0.8
    
# Content Organization
taxonomy:
  categories:
    - name: "Getting Started"
      tags: ["quickstart", "installation", "setup"]
    - name: "User Guides"
      tags: ["tutorials", "how-to", "examples"]
    - name: "API Documentation"
      tags: ["endpoints", "authentication", "integration"]
    - name: "AI Models"
      tags: ["bias-detection", "fairness", "algorithms"]
    - name: "Compliance"
      tags: ["privacy", "security", "legal"]
    - name: "Support"
      tags: ["faq", "troubleshooting", "contact"]

# Integration Settings
integrations:
  chatbot:
    provider: "chatbase"
    model: "gpt-4"
    knowledge_sync_interval: "1h"
    
  slack:
    workspace: "biasbuster"
    channels: ["#support", "#documentation"]
    
  github:
    repo: "biasbuster/docs"
    auto_update: true
    
  jira:
    project: "BIAS"
    auto_ticket: true

# Analytics Configuration
analytics:
  tracking:
    pageviews: true
    search_queries: true
    user_feedback: true
    content_performance: true
    
  alerts:
    knowledge_gaps: true
    outdated_content: true
    low_ratings: true
    search_failures: true

# Security Settings
security:
  encryption:
    at_rest: "AES-256"
    in_transit: "TLS 1.3"
    
  access_control:
    authentication: "JWT"
    rbac: true
    
  compliance:
    gdpr: true
    ccpa: true
    accessibility: "WCAG 2.1 AA"

# Automation Workflows
workflows:
  content_review:
    frequency: "daily"
    ai_analysis: true
    human_review: true
    
  content_generation:
    trigger: ["git_push", "jira_update"]
    review_required: true
    
  knowledge_sync:
    frequency: "hourly"
    platforms: ["chatbot", "slack", "api"]
