import React from 'react';

const TermsContent: React.FC = () => (
    <>
        <h4>1. Acceptance of Terms</h4>
        <p>By using Biasbuster ("the Service"), you agree to be bound by these Terms of Service. This is a demonstration project and is provided "as is" without any warranties.</p>
        
        <h4>2. Description of Service</h4>
        <p>The Service provides AI-powered analysis of text to detect potential bias. The analysis is generated by a large language model and may not always be accurate or complete. You should use the results as a guide and not as a definitive judgment.</p>

        <h4>3. User Conduct</h4>
        <p>You agree not to use the Service for any unlawful purpose or to submit any content that is illegal, defamatory, or infringes on the rights of others. You are responsible for the text you submit for analysis.</p>

        <h4>4. Disclaimer of Warranties</h4>
        <p>The Service is provided on an "as is" and "as available" basis. We expressly disclaim all warranties of any kind, whether express or implied, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</p>

        <h4>5. Limitation of Liability</h4>
        <p>In no event shall the creator of Biasbuster be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or the inability to use the Service.</p>
    </>
);

export default TermsContent;