name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Prevent multiple workflow runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        if [ $? -ne 0 ]; then
          echo "::error::Dependencies installation failed"
          exit 1
        fi

    
    - name: Build
      run: |
        npm run build
        if [ $? -ne 0 ]; then
          echo "::error::Build process failed"
          exit 1
        fi
    
    - name: Run tests
      run: |
        npm test
        if [ $? -ne 0 ]; then
          echo "::error::Tests failed"
          exit 1
        fi

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          dist
          build
          .next
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-

  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
        config-file: .github/codeql/codeql-config.yml

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:javascript"
